/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_carrotsearch_ant_tasks_junit4_tests_Crash */

#ifndef _Included_com_carrotsearch_ant_tasks_junit4_tests_Crash
#define _Included_com_carrotsearch_ant_tasks_junit4_tests_Crash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_carrotsearch_ant_tasks_junit4_tests_Crash
 * Method:    crashMe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_carrotsearch_ant_tasks_junit4_tests_Crash_crashMe
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
